services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./data/:/app/data/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: on-failure
